version: '3'

services:
  php:
      container_name: conference_php
      build: ./docker/php
      image: conference-php
      volumes:
          - ./:/var/www/conference
          - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
      extra_hosts:
          # Ensure that host.docker.internal is correctly defined on Linux
          - host.docker.internal:host-gateway
  worker:
      container_name: messenger_worker
      image: conference-php
      restart: unless-stopped
      command: php /var/www/conference/bin/console messenger:consume async --time-limit=3600
      volumes:
          - ./:/var/www/conference
      depends_on:
          rabbitmq:
            condition: service_healthy
  nginx:
      container_name: conference_nginx
      image: nginx:stable-alpine
      ports:
          - "80:80"
      volumes:
          - ./:/var/www/conference
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
###> doctrine/doctrine-bundle ###
  database:
    container_name: conference_database
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  redis:
    container_name: conference_redis
    image: redis:5-alpine
    ports: [6379]

  rabbitmq:
    container_name: conference_rabbitmq
    image: rabbitmq:3-management
    ports: [5672, 15672]
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
networks:
  default:
    name: conference_app